image: alpine/edge
oauth: pages.sr.ht/PAGES:RW
packages:
- hut
environment:
  site: rabbits.srht.site
sources:
    - https://git.sr.ht/~rabbits/solrela
tasks:
    - package: |
        cd solrela
        tar -czf ../out.tar.gz index.html media/ src/
    - upload: 
        hut pages publish -d $site -s /solrela  out.tar.gz
