image: debian/stable
oauth: pages.sr.ht/PAGES:RW
environment:
    SITE: rabbits.srht.site/solrela
sources:
    - https://git.sr.ht/~rabbits/solrela
tasks:
    - upload: |
        cd solrela
        tar -czf out.tar.gz index.html src/
        acurl() {
            set +x
            curl -H "Authorization: Bearer ${OAUTH2_TOKEN}" "${@}"
            set -x
        }
        acurl -fsS "https://pages.sr.ht/publish/${SITE}" -Fcontent=@out.tar.gz
