let dict=`Solresol Dictionary,,
"Translated from François Sudre's original definitions by Garrison Osteen 
Gradually modified and edited by the Solresol Community",,
,,
First Part,,
Solresol,English,Comments
Do,"No, not, nor",
Re,And,
Mi,Or,
Fa,"At, to",
Sol,If,
La,The,
Si,"Yes, willingly",
,,
"Binary Combinations - Dedicated to Small Words, to the Most Common Particles, and to Pronouns",,
Dore,"I, me, myself, personally, we, ourselves",
Domi,"You, yourself, (singular or plural)",
Dofa,"He, she, it, him, her, them, they",
Dosol,"Self, oneself",
Dola,"One, someone, another person",
Dosi,"Other, another, different, alternative",
Redo,"My, mine",
Remi,"Your, yours",
Refa,"His, her, its",
Resol,"Our, ours",
Rela,"Your, yours (plural)",
Resi,"Their, theirs",
Mido,For,
Mire,"That, which, who",
Mifa,Whose,
Misol,"Well, well done, good","Musical meaning derived from ""God"""
Mila,"Voila, behold, here is",
Misi,"Good evening, good night",
Fado,"What?, what is this?",
Fare,"That, that one, those (people or things)",
Fami,"This, this one, these (people or things)",
Fasol,"Here, here is, this is",
Fala,"Good, tasty, delectable, exquisite, delicious",
Fasi,"Much, very, a lot, many (augmentative)",
Soldo,"Nothing, nil, naught, null",
Solre,Why? What for?,
Solmi,"Wrong, evil","Derived from ""Satan"""
Solfa,"Because, for",
Solla,"Always, perpetuate, perpetuately, constantly",
Solsi,"Thanks, thank",
Lado,Yesterday,
Lare,"Today, this day",
Lami,Tomorrow,
Lafa,Bad,
Lasol,Never,
Lasi,Of,
Sido,How,
Sire,"Each, every",
Simi,"Good morning/afternoon, hello",
Sifa,"Little, scarcely",
Sisol,"Mister, sir",
Sila,"Madame, Ms",
`